name: app_for_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter 
  firebase_core: ^3.10.0   
  firebase_auth: ^5.0.0
  firebase_data_connect: ^0.1.2+6
  firebase_ui_auth: ^1.16.1
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
